import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/molecules/sideBar";
import LinkBar from "@/components/molecules/linkBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Diego Alejandro Carvajal Díaz Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <section className="flex bg-gray-900 min-h-screen w-full justify-center md:pl-64">
          {/* Sidebar */}
          <SideBar />
          {children}
          <LinkBar />
        </section>
      </body>
    </html>
  );
}
